### PR TITLE
Build script modifications

### PR DESCRIPTION
**Pull request by mscappini**

### CODE REVIEW

**Comment by aisthesis** [comment]
Sorry, I only just now saw that there was a pull request open for this.

**Comment by aisthesis** [comment]
You might make a note in the README that it hangs quite a while on `npm install`. It finally succeeded, but it took a fair while (maybe 5 minutes?) for some reason--just so people don't give up when doing the install.

**Comment by aisthesis** [comment]
On `npm start` I get the same thing:

$ npm start

> @optbot/restapi@0.0.1 start /mnt/disk1/home/marshall/workspace/restapi
> node lib/app.js

module.js:340
    throw err;
          ^
Error: Cannot find module './config.production.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/mnt/disk1/home/marshall/workspace/restapi/lib/config/config.js:2:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.25
npm ERR! npm  v2.7.6
npm ERR! code ELIFECYCLE
npm ERR! @optbot/restapi@0.0.1 start: `node lib/app.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the @optbot/restapi@0.0.1 start script 'node lib/app.js'.
npm ERR! This is most likely a problem with the @optbot/restapi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls @optbot/restapi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/disk1/home/marshall/workspace/restapi/npm-debug.log

Maybe you're overthinking the production/dev distinction at this point. Our current environments have no way of telling whether they're production or not. Sure, in the future we'll need to make that distinction, but if it's making the code too complicated, I wouldn't worry about it for now.

**Comment by aisthesis** [comment]
You should also make a 'Connects to' section with a note that the service needs to connect to a mongo instance with a populated 'quotes' collection, as well as anything else that's required but not universally present on our server(s).

**Comment by mscappini** [comment]
Regarding the stalling on `npm install`, it's probably because it compiles the Mongo core Kerberos driver using [node-gyp](https://github.com/TooTallNate/node-gyp#node-gyp).

Same problem on `npm start` as `ui` project. Missing config files. I will fix this.

I will update the README to show the "Connects To" piece.

**Comment by mscappini** [comment]
Please have another go on the server.

**Comment by aisthesis** [comment]
Server is starting now, but I'm not getting anything. Here's what console shows:

$ npm start

> @optbot/restapi@0.0.1 start /mnt/disk1/home/marshall/workspace/restapi
> node lib/app.js

Express server started at http://0.0.0.0:8081

The server IP is 192.168.56.101, yet when I type into Firefox `http://192.168.56.101:8080/api/?equity=SCTY&option=call&strike=30&expiry=2015-4-9`, I get:

Unable to connect

Firefox can't establish a connection to the server at 192.168.56.101:8080.

Yet when I ping:

$ ping 192.168.56.101
PING 192.168.56.101 (192.168.56.101): 56 data bytes
64 bytes from 192.168.56.101: icmp_seq=0 ttl=64 time=0.517 ms
...

**Comment by aisthesis** [comment]
Ah, looks like you're running it on port 8081 by default. When I change the port, it works.

Please change port in documentation or in code.

**Comment by mscappini** [comment]
Yes, the `restapi` port is 8081 in case `ui` runs on the same machine.

**Comment by aisthesis** [comment]
Ship it!

**Pull request merged**
